interfaces:
  - interface1:
    config: set
    name: et-0/0/12
    unit: 0
    vlan: vlan101
    mode: trunk
    mtu: 9192
    description: "ansible test"

  - interface2:
    config: set
    name: et-0/0/13
    unit: 0
    vlan: vlan101
    mode: access
    mtu: 9192
    description: "ansible test"

vlans:
  - vlan1:
    config: set
    vlan: vlan101
    id: 101
    l3interface: irb.101
    description: "Testing_config"
    igmp_interface: irb.101
    igmp_vlan: vlan101
    igmp_address: 10.1.93.252

