interfaces:
  - interface1:
    config: 
    name: 
    unit: 
    vlan: 
    mode: 
    mtu: 
    description:

  - interface2:
    config:
    name: 
    unit: 
    vlan: 
    mode: 
    mtu: 
    description: 

vlans:
  - vlan1:
    config: set
    vlan: vlan101
    id: 101
    l3interface: irb.101
    description: "Testing_config"
    igmp_interface: irb.101
    igmp_vlan: vlan101
    igmp_address: 10.1.93.252

