host:
  management:
    ip: 10.8.148.6
    mask: 24

user:
  name: col
  password: col123col

interfaces: 
  - interface1:
    name: et-0/0/12
    unit:
    vlan:
    mode:
    mtu:
    description: "ansible test"

  - interface2:
    name: et-0/0/13
    name: et-0/0/12
    unit:
    vlan:
    mode:
    mtu:
    description: "ansible test"

vlans:
  - vlan1:
    vlan:
    id:
    l3interface:
    description:
    igmp-interface:
    igmp-vlan:
    igmp-address:

l3interfaces:
  - l3interface1:
    interface:
    unit:
    description:
    inet-address:
    vrrp:
    virtual:

VRs:
  - VR1:
    instances: 
    interface:
    area:
    interface-type:
    metric:
    passive: yes

routes:
  - route1:
    instances:
    route:
    nexthop:

filters:
  - filter1:
    firewall:
    filter:
    term:
    from:
    accept: yes
