---
- name: Build configuration for Forti devices
  hosts: Firewall
  connection: local
  gather_facts: no

  vars_files:
    - host_vars/{{ inventory_hostname }}.yaml

  tasks:
  - name: Build the configuration file from host variable
    template:
      src: "/etc/ansible/roles/Fortigate/templates/forti.txt.j2"
      dest: "/etc/ansible/config/{{ inventory_hostname }}.txt"

  - include: install_f.yaml
