---
- name: Build the spine configuration for Junos devices
  hosts: Spine
  connection: local
  gather_facts: no

  vars_files:
    - host_vars/{{ inventory_hostname }}.yaml

  tasks:
  - name: Build the configuration file from host variable
    template:
      src: "/etc/ansible/roles/Junos/templates/spine.txt.j2"
      dest: "/etc/ansible/config/{{ inventory_hostname }}.txt"
