---
- name: Load the configuration to Forti devices
  hosts: Firewall
  roles:
  - Fortigate
  connection: local
  gather_facts: no

  tasks: 
  - name: Load the configuration file
    st_install_forti_v2: 
      host={{ inventory_hostname }}
      file=/etc/ansible/config/ST_{{ inventory_hostname }}.txt
      vdom=test
    register: testout
  - name: dump output
    debug:
      msg: '{{ testout }}'
